// Catalogue de départ des pathologies, codes CIM-10 (OMS) et libellés français,
// regroupés par spécialité. Jeu curé et NON exhaustif : l'administrateur peut en
// ajouter/retirer depuis l'application (table `pathologies`).

export interface SeedPathology {
  code: string; // code CIM-10
  label: string;
}

export const PATHOLOGIES: Record<string, SeedPathology[]> = {
  GENERAL: [
    { code: 'B54', label: 'Paludisme, sans précision' },
    { code: 'A09', label: 'Diarrhée et gastro-entérite d’origine infectieuse présumée' },
    { code: 'J06', label: 'Infection aiguë des voies respiratoires supérieures' },
    { code: 'J18', label: 'Pneumonie, micro-organisme non précisé' },
    { code: 'A01', label: 'Fièvre typhoïde et paratyphoïde' },
    { code: 'K29', label: 'Gastrite et duodénite' },
    { code: 'I10', label: 'Hypertension essentielle (primitive)' },
    { code: 'E11', label: 'Diabète sucré de type 2' },
    { code: 'R50', label: 'Fièvre d’origine non précisée' },
    { code: 'R51', label: 'Céphalée' },
    { code: 'N39', label: 'Infection des voies urinaires, siège non précisé' },
    { code: 'B82', label: 'Parasitose intestinale, sans précision' },
    { code: 'D50', label: 'Anémie par carence en fer' },
    { code: 'J45', label: 'Asthme' },
    { code: 'M54', label: 'Dorsalgie' },
  ],
  GYNECOLOGIE: [
    { code: 'N70', label: 'Salpingite et ovarite' },
    { code: 'N71', label: 'Maladie inflammatoire de l’utérus (sauf col)' },
    { code: 'N72', label: 'Maladie inflammatoire du col de l’utérus' },
    { code: 'N76', label: 'Autres affections inflammatoires du vagin et de la vulve' },
    { code: 'N80', label: 'Endométriose' },
    { code: 'N81', label: 'Prolapsus génital de la femme' },
    { code: 'N83', label: 'Affections non inflammatoires de l’ovaire et de la trompe (kyste ovarien)' },
    { code: 'N84', label: 'Polype de l’appareil génital féminin' },
    { code: 'N85', label: 'Hyperplasie de l’endomètre' },
    { code: 'N91', label: 'Aménorrhée / règles peu abondantes' },
    { code: 'N92', label: 'Règles abondantes, fréquentes ou irrégulières' },
    { code: 'N93', label: 'Autres saignements anormaux de l’utérus et du vagin' },
    { code: 'N94', label: 'Douleurs et affections liées aux organes génitaux et au cycle menstruel' },
    { code: 'N95', label: 'Troubles de la ménopause et de la périménopause' },
    { code: 'N97', label: 'Stérilité de la femme' },
    { code: 'O00', label: 'Grossesse extra-utérine' },
    { code: 'O03', label: 'Avortement spontané' },
    { code: 'O20', label: 'Hémorragie du début de la grossesse' },
    { code: 'Z34', label: 'Surveillance d’une grossesse normale' },
    { code: 'Z30', label: 'Prise en charge contraceptive' },
  ],
  DERMATOLOGIE: [
    { code: 'L01', label: 'Impétigo' },
    { code: 'L02', label: 'Abcès cutané, furoncle et anthrax' },
    { code: 'L03', label: 'Cellulite (dermohypodermite)' },
    { code: 'L20', label: 'Dermatite atopique (eczéma)' },
    { code: 'L21', label: 'Dermatite séborrhéique' },
    { code: 'L23', label: 'Dermatite de contact allergique' },
    { code: 'L29', label: 'Prurit' },
    { code: 'L40', label: 'Psoriasis' },
    { code: 'L43', label: 'Lichen plan' },
    { code: 'L50', label: 'Urticaire' },
    { code: 'L70', label: 'Acné' },
    { code: 'L71', label: 'Rosacée' },
    { code: 'L80', label: 'Vitiligo' },
    { code: 'B35', label: 'Dermatophytose (teigne, mycose de la peau)' },
    { code: 'B36', label: 'Autres mycoses superficielles' },
    { code: 'B00', label: 'Infections à virus herpès simplex' },
    { code: 'B07', label: 'Verrues virales' },
    { code: 'L98', label: 'Autres affections de la peau et du tissu cutané' },
  ],
  OPHTALMOLOGIE: [
    { code: 'H00', label: 'Orgelet et chalazion' },
    { code: 'H01', label: 'Blépharite et autres inflammations de la paupière' },
    { code: 'H10', label: 'Conjonctivite' },
    { code: 'H16', label: 'Kératite' },
    { code: 'H25', label: 'Cataracte sénile' },
    { code: 'H26', label: 'Autres cataractes' },
    { code: 'H33', label: 'Décollement et déchirures de la rétine' },
    { code: 'H35', label: 'Autres affections de la rétine (rétinopathie)' },
    { code: 'H40', label: 'Glaucome' },
    { code: 'H43', label: 'Affections du corps vitré' },
    { code: 'H52.0', label: 'Hypermétropie' },
    { code: 'H52.1', label: 'Myopie' },
    { code: 'H52.2', label: 'Astigmatisme' },
    { code: 'H52.4', label: 'Presbytie' },
    { code: 'H53', label: 'Troubles visuels subjectifs' },
    { code: 'H57', label: 'Autres affections de l’œil et de ses annexes' },
  ],
  KINE: [
    { code: 'M16', label: 'Coxarthrose (arthrose de la hanche)' },
    { code: 'M17', label: 'Gonarthrose (arthrose du genou)' },
    { code: 'M19', label: 'Autres arthroses' },
    { code: 'M23', label: 'Lésion interne du genou (ménisque)' },
    { code: 'M25', label: 'Autres affections articulaires (douleur, raideur)' },
    { code: 'M42', label: 'Ostéochondrose de la colonne vertébrale' },
    { code: 'M47', label: 'Spondylarthrose' },
    { code: 'M51', label: 'Atteintes des disques intervertébraux (hernie discale)' },
    { code: 'M54.5', label: 'Lombalgie basse' },
    { code: 'M62', label: 'Autres atteintes musculaires' },
    { code: 'M75', label: 'Lésions de l’épaule' },
    { code: 'M77', label: 'Autres enthésopathies (épicondylite, etc.)' },
    { code: 'I69', label: 'Séquelles d’accident vasculaire cérébral (hémiplégie)' },
    { code: 'G80', label: 'Paralysie cérébrale (infirmité motrice)' },
    { code: 'S83', label: 'Entorse et foulure du genou' },
    { code: 'S93', label: 'Entorse et foulure de la cheville et du pied' },
    { code: 'T92', label: 'Séquelles de traumatismes du membre supérieur' },
    { code: 'T93', label: 'Séquelles de traumatismes du membre inférieur' },
    { code: 'Z50', label: 'Soins de rééducation' },
  ],
  RADIOLOGIE: [
    { code: 'Z01.8', label: 'Examen d’imagerie / échographie de dépistage' },
    { code: 'O36', label: 'Surveillance échographique de la grossesse' },
    { code: 'N83', label: 'Kyste ovarien (échographie pelvienne)' },
    { code: 'D25', label: 'Léiomyome de l’utérus (fibrome)' },
    { code: 'K80', label: 'Lithiase biliaire (échographie abdominale)' },
    { code: 'K76', label: 'Autres maladies du foie (stéatose, etc.)' },
    { code: 'N20', label: 'Calcul du rein et de l’uretère' },
    { code: 'N28', label: 'Autres affections du rein et de l’uretère' },
    { code: 'E04', label: 'Goitre non toxique (échographie thyroïdienne)' },
    { code: 'I74', label: 'Embolie et thrombose artérielles (Doppler)' },
    { code: 'I80', label: 'Phlébite et thrombophlébite (Doppler veineux)' },
    { code: 'R93', label: 'Résultats anormaux d’imagerie diagnostique' },
    { code: 'R19.0', label: 'Masse ou tuméfaction intra-abdominale' },
    { code: 'Z36', label: 'Dépistage anténatal' },
  ],
};
